version: '3.1'
services:
  pokedexapp:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: pokedex-docker
    container_name: pokedexapp
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    # working_dir: /var/www/pokedex
    environment:
      MONGODB: ${MONGODB_CONNECTION}
      PORT: ${SERVER_PORT}
      DEFAULT_LIMIT: ${POKEAPI_LIMIT}
    # volumes:
    #   - ./:/var/www/pokedex
  db:
    image: mongo:5.0.0
    container_name: mongo-poke
    restart: always
    ports:
      - 27017:27017
    # volumes:
    #   - ./mongo:/data/db
    environment:
      MONGO_INITDB_DATABASE: nest-pokemon